FROM python:latest

RUN mkdir -p /usr/feedback_backend

COPY . /usr/feedback_backend

WORKDIR /usr/feedback_backend

RUN pip install -r requirements.txt 
RUN pip install gunicorn

CMD ["gunicorn", "-w 4", "-b 0.0.0.0:5000", "main:app"]