FROM python:alpine

WORKDIR /app

COPY ./requirements.txt .

RUN pip install --upgrade pip

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["fastapi", "run", "api/__init__.py", "--port", "8000"]

